server:
  port: 8081

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # PC에 만들어놓은 Database 이름 사용
    url: jdbc:mysql://localhost:3306/simpleMember_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # mysql에 생성한 사용자 계정 정보
    username: wonbeen
    password: 1234
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      show-sql: true
      properties:
        hibernate.format_sql: true
        dialect: org.hibernate.dialect.MySQLInnoDBDialect


